export { default as Home } from './Home/Home.jsx'
export { default as TechStack } from './TechStack/TechStack.jsx'
export { default as Project } from './Project/Project.jsx'
export { default as Tutor } from './Tutor/Tutor.jsx'
export { default as Experience } from './Experience/Experience.jsx'